SELECT ?term ?description ?source ?url_source WHERE {
  VALUES ?target {
    wd:Q1411457
    wd:Q8161
  }
  ?item (wdt:P31/(wdt:P279*)) ?target;
    wdt:P1001 wd:Q142;
    wdt:P1813 ?term;
    rdfs:label ?description.
  FILTER((LANG(?description)) = "fr")
  BIND(?item AS ?url_source)
  VALUES ?source {
    "Wikidata"
  }
}
ORDER BY (?term)
